version: '3.7'

services:
  hotels-api:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:debug
    depends_on:
      - mongo-db
    environment:
      - MONGO_DB_CONNECTION=mongodb://mongo-db:27017/hotels-api
  mongo-db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - hotels-api-mongo-db:/data/db
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db

volumes:
  hotels-api-mongo-db:
    driver: local
